#!/bin/bash


########################################
### Android ADB SHELL By Mint Fans
########################################
ADB=/usr/bin/adb
CLEAR=/usr/bin/clear
#########################################
msg_fun(){
$CLEAR
echo -e ""
echo -e "    $TITLE"
echo -e ""
echo -e "    $TEXT"
echo -e ""
read MSG
}

#########################################
shell_fun(){
$CLEAR
echo -e ""
echo -e "    執行SHELL命令"
echo -e ""
echo -e "    輸入單一命令，或者直接按ENTER進入SHELL"
echo -e ""
read CMD
[[ "$CMD" ]]

$ADB remount
$ADB shell $CMD

main_fun
}

#########################################
inst_fun(){
$CLEAR
echo -e ""
echo -e "    安裝 APK"
echo -e ""
echo -e "    拖放APK檔案到此"
echo -e ""
read FILE
[[ "$FILE" ]]

read FILE
[[ "$FILE" ]]
if [ "$FILE" == "" ]; then
    main_fun
fi

$ADB install $FILE

TITLE="安裝 APK"
TEXT="安裝 APK 完成!"
msg_fun
main_fun


}
#########################################
chmod_fun(){
$CLEAR
echo -e ""
echo -e "    修復系統檔案權限"
echo -e ""
echo -e "    輸入要修復的檔案"
echo -e ""
read FILE
[[ "$FILE" ]]
if [ "$FILE" == "" ]; then
    main_fun
fi

echo -e ""
echo -e "    設置權限"
echo -e "    範例 06755、0755、0644"
echo -e ""
read CHMOD
[[ "$CHMOD" ]]
if [ "$CHMOD" == "" ]; then
    main_fun
fi

$ADB shell chown 0.0 $FILE
$ADB shell chmod $CHMOD $FILE

TITLE="修復系統檔案權限"
TEXT="修復權限完成!"
msg_fun
main_fun

}

#########################################
pull_fun(){
$CLEAR
echo -e ""
echo -e "    從安卓提取檔案"
echo -e ""
echo -e "    輸入要提取的檔案"
echo -e ""
read FILE
[[ "$FILE" ]]

if [ "$FILE" == "" ]; then
    main_fun
fi

DIR_NAME=$(dirname $FILE)
BASE_NAME=$(basename $FILE)

mkdir -p $HOME/Android/$DIR_NAME
$ADB pull $FILE $HOME/Android/$DIR_NAME/$BASE_NAME

TITLE="從安卓提取檔案"
TEXT="從安卓提取檔案完成!"
msg_fun
main_fun

}
#########################################
push_fun(){
$CLEAR
echo -e ""
echo -e "    複製檔案到安卓"
echo -e ""
echo -e "    拖放檔案到此"
echo -e ""
read FILE
[[ "$FILE" ]]
if [ "$FILE" == "" ]; then
    main_fun
fi

echo -e ""
echo -e "    輸入複製到安卓的路徑"
echo -e ""
echo -e "    範例 /system/bin/"
echo -e ""
read PATH
[[ "$PATH" ]]

if [ "$PATH" == "" ]; then
    main_fun
fi

$ADB remount
$ADB push $FILE $PATH

TITLE="複製檔案到安卓"
TEXT="複製檔案到安卓完成!"
msg_fun
main_fun

}

#########################################
main_fun(){
$CLEAR
echo -e ""
echo -e "    Android ADB SHELL"
echo -e ""
echo -e "    1) 複製檔案到安卓"
echo -e ""
echo -e "    2) 從安卓提取檔案"
echo -e ""
echo -e "    3) 修復系統檔案權限"
echo -e ""
echo -e "    4) 安裝 APK"
echo -e ""
echo -e "    5) 執行SHELL命令"
echo -e ""
echo -e "    6) 進入recovery模式"
echo -e ""
echo -e "    7) 進入fastboot模式"
echo -e ""
echo -e "    0) EXIT"
echo -e ""
read MAIN
[[ "$MAIN" ]]

if [ "$MAIN" == "1" ]; then
    push_fun
elif [ "$MAIN" == "2" ]; then
    pull_fun
elif [ "$MAIN" == "3" ]; then
    chmod_fun
elif [ "$MAIN" == "4" ]; then
    inst_fun
elif [ "$MAIN" == "5" ]; then
    shell_fun
elif [ "$MAIN" == "6" ]; then
    adb reboot recovery
elif [ "$MAIN" == "7" ]; then
    adb reboot bootloader
else
    exit
fi
}

main_fun
