#!/bin/bash


RUN_IN_CHROOT="chroot /mnt/ /bin/bash -c"

SNAPSHOT=20160315T035914Z
LIST_DIR=list-20160315

rm -rf /mnt/usr/share/apt
mkdir -p /mnt/usr/share/apt
mkdir -p /mnt/usr/share/apt/$LIST_DIR

$RUN_IN_CHROOT "wget http://snapshot.debian.org/archive/debian/$SNAPSHOT/dists/sid/main/binary-amd64/Packages.gz"
$RUN_IN_CHROOT "gunzip Packages.gz"
$RUN_IN_CHROOT "mv Packages /usr/share/apt/$LIST_DIR/snapshot.debian.org_archive_debian_$SNAPSHOT_dists_sid_main_binary-amd64_Packages"

$RUN_IN_CHROOT "wget http://snapshot.debian.org/archive/debian/$SNAPSHOT/dists/sid/Release"
$RUN_IN_CHROOT "mv Release /usr/share/apt/$LIST_DIR/snapshot.debian.org_archive_debian_$SNAPSHOT_dists_sid_Release"

$RUN_IN_CHROOT "wget http://snapshot.debian.org/archive/debian/$SNAPSHOT/dists/sid/Release.gpg"
$RUN_IN_CHROOT "mv Release.gpg /usr/share/apt/$LIST_DIR/snapshot.debian.org_archive_debian_$SNAPSHOT_dists_sid_Release.gpg"

$RUN_IN_CHROOT "wget http://snapshot.debian.org/archive/debian/$SNAPSHOT/dists/sid/contrib/binary-amd64/Packages.gz"
$RUN_IN_CHROOT "gunzip Packages.gz"
$RUN_IN_CHROOT "mv Packages /usr/share/apt/$LIST_DIR/snapshot.debian.org_archive_debian_$SNAPSHOT_dists_sid_contrib_binary-amd64_Packages"

$RUN_IN_CHROOT "wget http://snapshot.debian.org/archive/debian/$SNAPSHOT/dists/sid/non-free/binary-amd64/Packages.gz"
$RUN_IN_CHROOT "gunzip Packages.gz"
$RUN_IN_CHROOT "mv Packages /usr/share/apt/$LIST_DIR/snapshot.debian.org_archive_debian_$SNAPSHOT_dists_sid_non-free_binary-amd64_Packages"

$RUN_IN_CHROOT "wget http://snapshot.debian.org/archive/debian/$SNAPSHOT/dists/sid/InRelease"
$RUN_IN_CHROOT "mv InRelease /usr/share/apt/$LIST_DIR/snapshot.debian.org_archive_debian_$SNAPSHOT_dists_sid_InRelease"

cp /mnt/usr/share/apt/$LIST_DIR/* /mnt/var/lib/apt/lists/
