#!/bin/bash


########################################
### Debian Snapshot Switch By Mint Fans
########################################

###### Translations ###### 
	main01="Debian Snapshot Repository Switch"
	main02="Select Snapshot Repository"
	main03="Enable Snapshot Sources Repository"
	main04="Status"
	main05="Update APT Sources List"
	main06="Restore APT Sources List"
	main07="Enable i386 Repository"
	main08="EXIT"

	i38601="Enable i386 Repository"
	i38602="Options"

	switch01="Debian Snapshot Repository Switch"
	switch02="Enter Dates: year month day"
	switch03="for example"
	switch04="Press 0 to exit"

	smenu01="Select the distrib codename"
	smenu02="Press 0 to Back to Main Menu"

case $LANG in
	zh_TW* | zh_HK*)
	main01="Debian Snapshot 套件庫切換"
	main02="選擇 Snapshot 套件庫"
	main03="啟用 Snapshot 原始碼套件庫"
	main04="狀態"
	main05="更新 APT Sources List"
	main06="復原 APT Sources List"
	main07="啟用 i386 套件庫"
	main08="退出"

	i38601="啟用 i386 套件庫"
	i38602="選項"

	switch01="Debian Snapshot 套件庫切換"
	switch02="輸入日期: 年月日"
	switch03="範例"
	switch04="按「0」退出"

	smenu01="選擇發行版代號"
	smenu02="按0返回主選單"
esac

ENSRC='n'
DPKG_ARCH=$(cat /var/lib/dpkg/arch | grep i386)

if [ "$DPKG_ARCH" == "i386" ]; then
    DPKG_I386='y'
else
    DPKG_I386='n'
fi

main_fun(){
clear
echo -e ""
echo -e "    $main01"
echo -e ""
echo -e "    1) $main02"
echo -e "    2) $main03 ($main04: $ENSRC)"
echo -e "    3) $main05"

if [ -f "/etc/apt/backup/sources.list.gz" ] || [ -f "/etc/apt/backup/official-package-repositories.list.gz" ]; then
    echo -e "    4) $main06"
fi

if [ "$(uname -m)" == "x86_64" ]; then
    if [ ! "$DPKG_I386" == "y" ]; then
        echo -e "    5) $main07 (i386: $DPKG_I386)"
    fi
fi

echo -e "    0) $main08"

read MENU
[[ "$MENU" ]] && MENU="$MENU"

if [ "$MENU" == "1" ]; then
    switch_fun
elif [ "$MENU" == "2" ]; then
    ENSRC='y'
    main_fun
elif [ "$MENU" == "3" ]; then
    update_sources_fun
    exit
elif [ "$MENU" == "4" ]; then
    restore_sources_fun
elif [ "$MENU" == "5" ]; then
    i386_repo_fun
elif [ "$MENU" == "0" ]; then
    exit
else
    main_fun
fi

}

###########################################
#### Enable i386 Repository
###########################################
i386_repo_fun(){
clear
cat << ENTER
    $i38601

    ($main04: $DPKG_I386) $i38602[y/n]
ENTER

read DPKG_I386
[[ "$DPKG_I386" ]] && DPKG_I386="$DPKG_I386"
if [ ! "$DPKG_I386" == "y" ]; then
    DPKG_I386='n'
fi

if [ "$DPKG_I386" == "y" ]; then
    sudo dpkg --add-architecture i386
fi

main_fun

}

###########################################
#### Select Snapshot Repository
###########################################
switch_fun(){
clear
cat << ENTER

    $switch01


    $switch02
    $switch03: 20050312

    $switch04
ENTER

read DSR_DATE
[[ "$DSR_DATE" ]] && DSR_DATE="$DSR_DATE"

if [ "$DSR_DATE" -gt 0 ] 2>/dev/null ; then
    #### Debian Snapshot Set-up Time 2005-03-12
    if [ "$DSR_DATE" -ge "20050312" ]; then
        ### menu-01 20050312 - 20050606
        if [ "$DSR_DATE" -ge "20050312" ] && [ "$DSR_DATE" -le "20050606" ]; then
            menu01_fun
        ### menu-2 20050607 - 20070103
        elif [ "$DSR_DATE" -ge "20050607" ] && [ "$DSR_DATE" -le "20070103" ]; then
            menu02_fun
        ### menu-3 20070104 - 20070407
        elif [ "$DSR_DATE" -ge "20070104" ] && [ "$DSR_DATE" -le "20070407" ]; then
            menu03_fun
        ### menu-4 20070408 - 20081027
        elif [ "$DSR_DATE" -ge "20070408" ] && [ "$DSR_DATE" -le "20081027" ]; then
            menu04_fun
        ### menu-5 20081028 - 20090210
        elif [ "$DSR_DATE" -ge "20081028" ] && [ "$DSR_DATE" -le "20090210" ]; then
            menu05_fun
        ### menu-6 20090218 - 20100619
        elif [ "$DSR_DATE" -ge "20090218" ] && [ "$DSR_DATE" -le "20100619" ]; then
            menu06_fun
        ### menu-7 20100620 - 20100917
        elif [ "$DSR_DATE" -ge "20100620" ] && [ "$DSR_DATE" -le "20100917" ]; then
            menu07_fun
        ### menu-8 20100918 - 20101128
        elif [ "$DSR_DATE" -ge "20100918" ] && [ "$DSR_DATE" -le "20101128" ]; then
            menu08_fun
        ### menu-9 20101129 - 20110205
        elif [ "$DSR_DATE" -ge "20101129" ] && [ "$DSR_DATE" -le "20110205" ]; then
            menu09_fun
        ### menu-10 20110206 - 20120325
        elif [ "$DSR_DATE" -ge "20110206" ] && [ "$DSR_DATE" -le "20120325" ]; then
            menu10_fun
        ### menu-11 20120326 - 20121009
        elif [ "$DSR_DATE" -ge "20120326" ] && [ "$DSR_DATE" -le "20121009" ]; then
            menu11_fun
        ### menu-12 20121010 - 20130223
        elif [ "$DSR_DATE" -ge "20121010" ] && [ "$DSR_DATE" -le "20130223" ]; then
            menu12_fun
        ### menu-13 20130224 - 20130504
        elif [ "$DSR_DATE" -ge "20130224" ] && [ "$DSR_DATE" -le "20130504" ]; then
            menu13_fun
        ### menu-14 20130505 - 20131014
        elif [ "$DSR_DATE" -ge "20130505" ] && [ "$DSR_DATE" -le "20131014" ]; then
            menu14_fun
        ### menu-15 20131015 - 20140411
        elif [ "$DSR_DATE" -ge "20131015" ] && [ "$DSR_DATE" -le "20140411" ]; then
            menu15_fun
        ### menu-16 20140412 - 20141226
        elif [ "$DSR_DATE" -ge "20140412" ] && [ "$DSR_DATE" -le "20141226" ]; then
            menu16_fun
        ### menu-17 20141227 - 20150424
        elif [ "$DSR_DATE" -ge "20141227" ] && [ "$DSR_DATE" -le "20150424" ]; then
            menu17_fun
        ### menu-18 20150425 - 20160301
        elif [ "$DSR_DATE" -ge "20150425" ] && [ "$DSR_DATE" -le "20160301" ]; then
            menu18_fun
        ### menu-19 20160302 - 20160308
        elif [ "$DSR_DATE" -ge "20160302" ] && [ "$DSR_DATE" -le "20160308" ]; then
            menu19_fun
        ### menu-20 20160309 - 20160330
        elif [ "$DSR_DATE" -ge "20160309" ] && [ "$DSR_DATE" -le "20160330" ]; then
            menu20_fun
        ### menu-21 20160331 
        elif [ "$DSR_DATE" -ge "20160331" ]; then
            menu21_fun
        else
            switch_fun
        fi
    else
        switch_fun
    fi
else
    if [ "$DSR_DATE" == "0" ]; then
        exit
    else
        switch_fun
    fi
fi

}

###########################################
#### Update APT Sources List
###########################################
update_sources_fun(){
sudo rm /var/lib/apt/lists/*
sudo apt-get update
}
###########################################
#### Backup APT Sources List
###########################################
backup_sources_fun(){
sudo gzip /etc/apt/sources.list
sudo gzip /etc/apt/sources.list.d/official-package-repositories.list
sudo gzip /etc/apt/sources.list.d/official-source-repositories.list
sudo mkdir -p /etc/apt/backup
sudo mv /etc/apt/sources.list.gz /etc/apt/backup/
sudo mv /etc/apt/sources.list.d/official-package-repositories.list.gz /etc/apt/backup/
sudo mv /etc/apt/sources.list.d/official-source-repositories.list.gz /etc/apt/backup/
}

###########################################
#### Restore APT Sources List
###########################################
restore_sources_fun(){
echo -e "----> Restore APT Sources List..."
sudo rm -rf /etc/apt/sources.list
sudo rm -rf /etc/apt/sources.list.d/official-package-repositories.list
sudo rm -rf /etc/apt/sources.list.d/official-source-repositories.list
sudo rm -rf /etc/apt/sources.list.d/linuxmint-package-repositories.list
sudo rm -rf /etc/apt/sources.list.d/linuxmint-source-repositories.list
sudo mv /etc/apt/backup/sources.list.gz /etc/apt/
sudo mv /etc/apt/backup/official-package-repositories.list.gz /etc/apt/sources.list.d/
sudo mv /etc/apt/backup/official-source-repositories.list.gz /etc/apt/sources.list.d/
sudo gunzip /etc/apt/sources.list.gz
sudo gunzip /etc/apt/sources.list.d/official-package-repositories.list.gz
sudo gunzip /etc/apt/sources.list.d/official-source-repositories.list.gz
sudo rm -rf /etc/apt/backup
sudo rm /var/lib/apt/lists/*
apt_config_fun
sudo apt-get update
exit
# main_fun
}

###########################################
### APT Config
###########################################
apt_config_fun(){
cat > 00check-valid-until << EOF
Acquire::Check-Valid-Until "false";
EOF
sudo rm -rf /etc/apt/apt.conf.d/00check-valid-until
sudo mv 00check-valid-until /etc/apt/apt.conf.d/
}

###########################################
#### Get Snapshot Code
###########################################
get_snapshot_fun(){
wget https://github.com/Mint-Fans/linux-package/raw/debian/debian-snapshot-list.txt
SNAPSHOT=$(cat debian-snapshot-list.txt | grep $DSR_DATE | tail -n 1)
sudo rm debian-snapshot-list.txt
if [ "$SNAPSHOT" == "" ]; then
   switch_fun
fi
}

###########################################
#### Clear Sources List
###########################################
clear_sources_fun(){
sudo sh -c 'echo "#### Debian Snapshot Repository" > /etc/apt/sources.list'
sudo sh -c 'echo "#### Debian Snapshot Repository" > /etc/apt/sources.list.d/official-package-repositories.list'
sudo sh -c 'echo "#### Debian Snapshot Repository" > /etc/apt/sources.list.d/official-source-repositories.list'
}

###########################################
#### Write Sources List
###########################################
write_sources_fun(){

DISTRIB_ID=$(lsb_release -i | grep LinuxMint)
LSB_CODENAME=$(cat /etc/lsb-release | grep DISTRIB_CODENAME | sed -e 's/.*=//g')

if [ ! "$DISTRIB_ID" == "" ]; then
    IS_MINT='y'
fi

sudo sh -c "echo deb http://snapshot.debian.org/archive/debian/$SNAPSHOT $CODENAME main contrib non-free >> /etc/apt/sources.list.d/official-package-repositories.list"

if [ "$IS_MINT" == "y" ]; then
    sudo sh -c "echo deb http://packages.linuxmint.com/ $LSB_CODENAME main upstream import backport > /etc/apt/sources.list.d/linuxmint-package-repositories.list"
fi

if [ "$ENSRC" == "y" ]; then
    sudo sh -c "echo deb-src http://snapshot.debian.org/archive/debian/$SNAPSHOT $CODENAME main contrib non-free >> /etc/apt/sources.list.d/official-source-repositories.list"
    if [ "$IS_MINT" == "y" ]; then
        sudo sh -c "echo deb-src http://packages.linuxmint.com/ $LSB_CODENAME main upstream import backport > /etc/apt/sources.list.d/linuxmint-source-repositories.list"
    fi
fi
}

###########################################
#### MENU 01
###########################################
menu01_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) sarge
    3) woody
    4) experimental
    0) $smenu02
ENTER
read MENU01
[[ "$MENU01" ]] && MENU01="$MENU01"
if [ "$MENU01" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU01" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sarge
    write_sources_fun
    CODENAME=sarge-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU01" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=woody
    write_sources_fun
    CODENAME=woody-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU01" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU01" == "0" ]; then
    main_fun
else
    menu01_fun
fi

}

###########################################
#### MENU 02
###########################################
menu02_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) etch
    3) sarge
    4) woody
    5) experimental
    0) $smenu02
ENTER
read MENU02
[[ "$MENU02" ]] && MENU02="$MENU02"
if [ "$MENU02" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU02" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=etch
    write_sources_fun
    CODENAME=etch-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU02" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sarge
    write_sources_fun
    CODENAME=sarge-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU02" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=woody
    write_sources_fun
    CODENAME=woody-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU02" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU02" == "0" ]; then
    main_fun
else
    menu02_fun
fi

}
###########################################
#### MENU 03
###########################################
menu03_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) etch
    3) sarge
    4) experimental
    0) $smenu02
ENTER
read MENU03
[[ "$MENU03" ]] && MENU03="$MENU03"
if [ "$MENU03" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU03" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=etch
    write_sources_fun
    CODENAME=etch-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU03" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sarge
    write_sources_fun
    CODENAME=sarge-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU03" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU03" == "0" ]; then
    main_fun
else
    menu03_fun
fi

}

###########################################
#### MENU 04
###########################################
menu04_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) lenny
    3) etch
    4) sarge
    5) experimental
    0) $smenu02
ENTER
read MENU04
[[ "$MENU04" ]] && MENU04="$MENU04"
if [ "$MENU04" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU04" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=lenny
    write_sources_fun
    CODENAME=lenny-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU04" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=etch
    write_sources_fun
    CODENAME=etch-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU04" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sarge
    write_sources_fun
    CODENAME=sarge-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU04" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU04" == "0" ]; then
    main_fun
else
    menu04_fun
fi

}


###########################################
#### MENU 05
###########################################
menu05_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) lenny
    3) etch
    4) experimental
    0) $smenu02
ENTER
read MENU05
[[ "$MENU05" ]] && MENU05="$MENU05"
if [ "$MENU05" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU05" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=lenny
    write_sources_fun
    CODENAME=lenny-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU05" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=etch
    write_sources_fun
    CODENAME=etch-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU05" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU05" == "0" ]; then
    main_fun
else
    menu05_fun
fi

}

###########################################
#### MENU 06
###########################################
menu06_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) squeeze
    3) lenny
    4) etch
    5) experimental
    0) $smenu02
ENTER
read MENU06
[[ "$MENU06" ]] && MENU06="$MENU06"
if [ "$MENU06" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU06" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU06" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=lenny
    write_sources_fun
    CODENAME=lenny-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU06" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=etch
    write_sources_fun
    CODENAME=etch-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU06" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU06" == "0" ]; then
    main_fun
else
    menu06_fun
fi

}
###########################################
#### MENU 07
###########################################
menu07_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) squeeze
    3) lenny
    4) experimental
    0) $smenu02
ENTER
read MENU07
[[ "$MENU07" ]] && MENU07="$MENU07"
if [ "$MENU07" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU07" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU07" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=lenny
    write_sources_fun
    CODENAME=lenny-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU07" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU07" == "0" ]; then
    main_fun
else
    menu07_fun
fi

}

###########################################
#### MENU 08
###########################################
menu08_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) squeeze
    3) lenny
    4) experimental
    0) $smenu02
ENTER
read MENU08
[[ "$MENU08" ]] && MENU08="$MENU08"
if [ "$MENU08" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU08" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-volatile
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU08" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=lenny
    write_sources_fun
    CODENAME=lenny-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU08" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU08" == "0" ]; then
    main_fun
else
    menu08_fun
fi

}

###########################################
#### MENU 09
###########################################
menu09_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) squeeze
    3) lenny
    4) experimental
    0) $smenu02
ENTER
read MENU09
[[ "$MENU09" ]] && MENU09="$MENU09"
if [ "$MENU09" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU09" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU09" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=lenny
    write_sources_fun
    CODENAME=lenny-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU09" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU09" == "0" ]; then
    main_fun
else
    menu09_fun
fi

}

###########################################
#### MENU 10
###########################################
menu10_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) wheezy
    3) squeeze
    4) lenny
    5) experimental
    0) $smenu02
ENTER
read MENU10
[[ "$MENU10" ]] && MENU10="$MENU10"
if [ "$MENU10" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU10" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU10" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU10" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=lenny
    write_sources_fun
    CODENAME=lenny-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU10" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU10" == "0" ]; then
    main_fun
else
    menu10_fun
fi

}

###########################################
#### MENU 11
###########################################
menu11_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) wheezy
    3) squeeze
    4) experimental
    0) $smenu02
ENTER
read MENU11
[[ "$MENU11" ]] && MENU11="$MENU11"
if [ "$MENU11" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU11" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU11" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU11" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU11" == "0" ]; then
    main_fun
else
    menu11_fun
fi

}

###########################################
#### MENU 12
###########################################
menu12_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) wheezy
    3) squeeze
    4) experimental
    0) $smenu02
ENTER
read MENU12
[[ "$MENU12" ]] && MENU12="$MENU12"
if [ "$MENU12" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU12" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun
    CODENAME=wheezy-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU12" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU12" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU12" == "0" ]; then
    main_fun
else
    menu12_fun
fi

}

###########################################
#### MENU 13
###########################################
menu13_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) wheezy
    3) squeeze
    4) experimental
    0) $smenu02
ENTER
read MENU13
[[ "$MENU13" ]] && MENU13="$MENU13"
if [ "$MENU13" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU13" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-backports
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun
    CODENAME=wheezy-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU13" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU13" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU13" == "0" ]; then
    main_fun
else
    menu13_fun
fi

}

###########################################
#### MENU 14
###########################################
menu14_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) jessie
    3) wheezy
    4) squeeze
    5) experimental
    0) $smenu02
ENTER
read MENU14
[[ "$MENU14" ]] && MENU14="$MENU14"
if [ "$MENU14" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU14" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=jessie
    write_sources_fun
    CODENAME=jessie-proposed-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU14" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-backports
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun
    CODENAME=wheezy-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU14" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU14" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU14" == "0" ]; then
    main_fun
else
    menu14_fun
fi

}

###########################################
#### MENU 15
###########################################
menu15_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) jessie
    3) wheezy
    4) squeeze
    5) experimental
    0) $smenu02
ENTER
read MENU15
[[ "$MENU15" ]] && MENU15="$MENU15"
if [ "$MENU15" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU15" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=jessie
    write_sources_fun
    CODENAME=jessie-proposed-updates
    write_sources_fun
    CODENAME=jessie-backports
    write_sources_fun
    CODENAME=jessie-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU15" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-backports
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun
    CODENAME=wheezy-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU15" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU15" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU15" == "0" ]; then
    main_fun
else
    menu15_fun
fi

}

###########################################
#### MENU 16
###########################################
menu16_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) jessie
    3) wheezy
    4) squeeze
    5) experimental
    0) $smenu02
ENTER
read MENU16
[[ "$MENU16" ]] && MENU16="$MENU16"
if [ "$MENU16" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU16" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=jessie
    write_sources_fun
    CODENAME=jessie-proposed-updates
    write_sources_fun
    CODENAME=jessie-backports
    write_sources_fun
    CODENAME=jessie-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU16" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-backports
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun
    CODENAME=wheezy-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU16" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-lts
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU16" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU16" == "0" ]; then
    main_fun
else
    menu16_fun
fi

}

###########################################
#### MENU 17
###########################################
menu17_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) jessie
    3) wheezy
    4) squeeze
    5) experimental
    0) $smenu02
ENTER
read MENU17
[[ "$MENU17" ]] && MENU17="$MENU17"
if [ "$MENU17" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU17" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=jessie
    write_sources_fun
    CODENAME=jessie-proposed-updates
    write_sources_fun
    CODENAME=jessie-backports
    write_sources_fun
    CODENAME=jessie-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU17" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-backports
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun
    CODENAME=wheezy-updates
    write_sources_fun
    CODENAME=wheezy-backports-sloppy
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU17" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-lts
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU17" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU17" == "0" ]; then
    main_fun
else
    menu17_fun
fi

}

###########################################
#### MENU 18
###########################################
menu18_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) stretch
    3) jessie
    4) wheezy
    5) squeeze
    6) experimental
    0) $smenu02
ENTER
read MENU18
[[ "$MENU18" ]] && MENU18="$MENU18"
if [ "$MENU18" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU18" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=stretch
    write_sources_fun
    CODENAME=stretch-proposed-updates
    write_sources_fun
    CODENAME=stretch-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU18" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=jessie
    write_sources_fun
    CODENAME=jessie-proposed-updates
    write_sources_fun
    CODENAME=jessie-backports
    write_sources_fun
    CODENAME=jessie-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU18" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-backports
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun
    CODENAME=wheezy-updates
    write_sources_fun
    CODENAME=wheezy-backports-sloppy
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU18" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze
    write_sources_fun
    CODENAME=squeeze-lts
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU18" == "6" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU18" == "0" ]; then
    main_fun
else
    menu18_fun
fi

}

###########################################
#### MENU 19
###########################################
menu19_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) stretch
    3) jessie
    4) wheezy
    5) squeeze
    6) experimental
    0) $smenu02
ENTER
read MENU19
[[ "$MENU19" ]] && MENU19="$MENU19"
if [ "$MENU19" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU19" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=stretch
    write_sources_fun
    CODENAME=stretch-proposed-updates
    write_sources_fun
    CODENAME=stretch-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU19" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=jessie
    write_sources_fun
    CODENAME=jessie-proposed-updates
    write_sources_fun
    CODENAME=jessie-backports
    write_sources_fun
    CODENAME=jessie-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU19" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-backports
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun
    CODENAME=wheezy-updates
    write_sources_fun
    CODENAME=wheezy-backports-sloppy
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU19" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze-lts
    write_sources_fun
    CODENAME=squeeze-proposed-updates
    write_sources_fun
    CODENAME=squeeze-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU19" == "6" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU19" == "0" ]; then
    main_fun
else
    menu19_fun
fi

}

###########################################
#### MENU 20
###########################################
menu20_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) stretch
    3) jessie
    4) wheezy
    5) squeeze
    6) experimental
    0) $smenu02
ENTER
read MENU20
[[ "$MENU20" ]] && MENU20="$MENU20"
if [ "$MENU20" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU20" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=stretch
    write_sources_fun
    CODENAME=stretch-proposed-updates
    write_sources_fun
    CODENAME=stretch-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU20" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=jessie
    write_sources_fun
    CODENAME=jessie-proposed-updates
    write_sources_fun
    CODENAME=jessie-backports
    write_sources_fun
    CODENAME=jessie-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU20" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-backports
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun
    CODENAME=wheezy-updates
    write_sources_fun
    CODENAME=wheezy-backports-sloppy
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU20" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=squeeze-lts
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU20" == "6" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU20" == "0" ]; then
    main_fun
else
    menu20_fun
fi

}

###########################################
#### MENU 21
###########################################
menu21_fun(){
clear
cat << ENTER

    $smenu01

    1) sid
    2) stretch
    3) jessie
    4) wheezy
    5) experimental
    0) $smenu02
ENTER
read MENU21
[[ "$MENU21" ]] && MENU21="$MENU21"
if [ "$MENU21" == "1" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=sid
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU21" == "2" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=stretch
    write_sources_fun
    CODENAME=stretch-proposed-updates
    write_sources_fun
    CODENAME=stretch-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU21" == "3" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=jessie
    write_sources_fun
    CODENAME=jessie-proposed-updates
    write_sources_fun
    CODENAME=jessie-backports
    write_sources_fun
    CODENAME=jessie-updates
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU21" == "4" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=wheezy
    write_sources_fun
    CODENAME=wheezy-backports
    write_sources_fun
    CODENAME=wheezy-proposed-updates
    write_sources_fun
    CODENAME=wheezy-updates
    write_sources_fun
    CODENAME=wheezy-backports-sloppy
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU21" == "5" ]; then
    backup_sources_fun
    clear_sources_fun
    get_snapshot_fun

    CODENAME=experimental
    write_sources_fun

    ########
    apt_config_fun
    update_sources_fun
    exit

elif [ "$MENU21" == "0" ]; then
    main_fun
else
    menu21_fun
fi

}

main_fun
