#!/bin/bash

#################################################################
### debian stretch packages & source apt list 2016-03-29 22:02:50
#################################################################
# RUN_IN_CHROOT="chroot /mnt/ /bin/bash -c"

SNAPSHOT=20160329T220250Z
LIST_DIR=2016-03-29_22:02:50

# Architecture: all amd64 arm64 armel armhf hurd-i386 i386 kfreebsd-amd64 kfreebsd-i386 mips mips64el mipsel powerpc ppc64el s390x
# ARCH=i386
ARCH=amd64
CODEMAME=stretch

rm -rf /usr/share/apt
mkdir -p /usr/share/apt
mkdir -p /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-binary-"$ARCH"
mkdir -p /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-source

echo "deb http://snapshot.debian.org/archive/debian/"$SNAPSHOT" "$CODEMAME" main contrib non-free" >> /etc/apt/sources.list.d/official-package-repositories.list
echo "deb-src http://snapshot.debian.org/archive/debian/"$SNAPSHOT" "$CODEMAME" main contrib non-free" > /etc/apt/sources.list.d/official-source-repositories.list

wget http://snapshot.debian.org/archive/debian/"$SNAPSHOT"/dists/"$CODEMAME"/main/binary-"$ARCH"/Packages.xz
xz -d Packages.xz
rm *.xz
mv Packages /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-binary-"$ARCH"/snapshot.debian.org_archive_debian_"$SNAPSHOT"_dists_"$CODEMAME"_main_binary-"$ARCH"_Packages

wget http://snapshot.debian.org/archive/debian/"$SNAPSHOT"/dists/"$CODEMAME"/Release
mv Release /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-binary-"$ARCH"/snapshot.debian.org_archive_debian_"$SNAPSHOT"_dists_"$CODEMAME"_Release

wget http://snapshot.debian.org/archive/debian/"$SNAPSHOT"/dists/"$CODEMAME"/Release.gpg
mv Release.gpg /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-binary-"$ARCH"/snapshot.debian.org_archive_debian_"$SNAPSHOT"_dists_"$CODEMAME"_Release.gpg

wget http://snapshot.debian.org/archive/debian/"$SNAPSHOT"/dists/"$CODEMAME"/contrib/binary-"$ARCH"/Packages.xz
xz -d Packages.xz
rm *.xz
mv Packages /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-binary-"$ARCH"/snapshot.debian.org_archive_debian_"$SNAPSHOT"_dists_"$CODEMAME"_contrib_binary-"$ARCH"_Packages

wget http://snapshot.debian.org/archive/debian/"$SNAPSHOT"/dists/"$CODEMAME"/non-free/binary-"$ARCH"/Packages.xz
xz -d Packages.xz
rm *.xz
mv Packages /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-binary-"$ARCH"/snapshot.debian.org_archive_debian_"$SNAPSHOT"_dists_"$CODEMAME"_non-free_binary-"$ARCH"_Packages

wget http://snapshot.debian.org/archive/debian/"$SNAPSHOT"/dists/"$CODEMAME"/InRelease
mv InRelease /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-binary-"$ARCH"/snapshot.debian.org_archive_debian_"$SNAPSHOT"_dists_"$CODEMAME"_InRelease

### source
wget http://snapshot.debian.org/archive/debian/"$SNAPSHOT"/dists/"$CODEMAME"/main/source/Sources.xz
xz -d Sources.xz
rm *.xz
mv Sources /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-source/snapshot.debian.org_archive_debian_"$SNAPSHOT"_dists_"$CODEMAME"_main_source_Sources

wget http://snapshot.debian.org/archive/debian/"$SNAPSHOT"/dists/"$CODEMAME"/contrib/source/Sources.xz
xz -d Sources.xz
rm *.xz 
mv Sources /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-source/snapshot.debian.org_archive_debian_"$SNAPSHOT"_dists_"$CODEMAME"_contrib_source_Sources

wget http://snapshot.debian.org/archive/debian/"$SNAPSHOT"/dists/"$CODEMAME"/non-free/source/Sources.xz
xz -d Sources.xz
rm *.xz 
mv Sources /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-source/snapshot.debian.org_archive_debian_"$SNAPSHOT"_dists_"$CODEMAME"_non-free_source_Sources


cp /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-binary-"$ARCH"/* /var/lib/apt/lists/
cp /usr/share/apt/"$LIST_DIR"-"$CODEMAME"-source/* /var/lib/apt/lists/
