#!/bin/bash

#####################################################
ARCH=x86_64
COMMON=$1

[ -f "/usr/lib/firefox/firefox" ] && LIB64=lib
[ -f "/usr/lib64/firefox/firefox" ] && LIB64=lib64

###################################################
fp_download_fun(){
wget https://get.adobe.com/cz/flashplayer/npapiosx/ > /dev/null 2>&1
CURRENT_VER=$(cat index.html | grep Verze | sed 's/.*Verze //g' | sed 's/<.*//g')
rm -rf index.html
echo "download flash_player_npapi_linux.${ARCH}.tar.gz --->"
wget https://fpdownload.adobe.com/get/flashplayer/pdc/$CURRENT_VER/flash_player_npapi_linux.${ARCH}.tar.gz > /dev/null 2>&1
}

###################################################
fp_remove_fun(){
rm -rf /usr/share/icons/hicolor/16x16/apps/flash-player-properties.png
rm -rf /usr/share/icons/hicolor/22x22/apps/flash-player-properties.png
rm -rf /usr/share/icons/hicolor/24x24/apps/flash-player-properties.png
rm -rf /usr/share/icons/hicolor/32x32/apps/flash-player-properties.png
rm -rf /usr/share/icons/hicolor/48x48/apps/flash-player-properties.png
rm -rf /usr/share/pixmaps/flash-player-properties.png
rm -rf /usr/share/applications/flash-player-properties.desktop
rm -rf /usr/bin/flash-player-properties
rm -rf /usr/share/kde4/services/kcm_adobe_flash_player.desktop
rm -rf /usr/lib64/kde4/kcm_adobe_flash_player.so
rm -rf /usr/lib/kde4/kcm_adobe_flash_player.so
rm -rf /usr/$LIB64/mozilla/plugins/libflashplayer.so
echo "adobe flashplayer uninstall completed --->"
}

###################################################
fp_install_fun(){
mkdir -p flash_player
cd flash_player
tar zxvf ../flash_player_npapi_linux.${ARCH}.tar.gz

install -D -m644 usr/share/icons/hicolor/16x16/apps/flash-player-properties.png /usr/share/icons/hicolor/16x16/apps/flash-player-properties.png
install -D -m644 usr/share/icons/hicolor/22x22/apps/flash-player-properties.png /usr/share/icons/hicolor/22x22/apps/flash-player-properties.png
install -D -m644 usr/share/icons/hicolor/24x24/apps/flash-player-properties.png /usr/share/icons/hicolor/24x24/apps/flash-player-properties.png
install -D -m644 usr/share/icons/hicolor/32x32/apps/flash-player-properties.png /usr/share/icons/hicolor/32x32/apps/flash-player-properties.png
install -D -m644 usr/share/icons/hicolor/48x48/apps/flash-player-properties.png /usr/share/icons/hicolor/48x48/apps/flash-player-properties.png
install -D -m644 usr/share/icons/hicolor/48x48/apps/flash-player-properties.png /usr/share/pixmaps/flash-player-properties.png
install -D -m755 usr/bin/flash-player-properties /usr/bin/flash-player-properties

install -D -m644 usr/share/applications/flash-player-properties.desktop /usr/share/applications/flash-player-properties.desktop

if [ -d "/usr/share/kde4/services" ]; then
    install -D -m644 usr/share/kde4/services/kcm_adobe_flash_player.desktop /usr/share/kde4/services/kcm_adobe_flash_player.desktop
fi

if [ -d "/usr/lib64/kde4" ]; then
    install -D -m755 usr/lib64/kde4/kcm_adobe_flash_player.so /usr/$LIB64/kde4/kcm_adobe_flash_player.so
fi

if [ -d "/usr/lib/kde4" ]; then
    install -D -m755 usr/lib64/kde4/kcm_adobe_flash_player.so /usr/$LIB64/kde4/kcm_adobe_flash_player.so
fi

mkdir -p /usr/$LIB64/mozilla/plugins
install -D -m755 libflashplayer.so /usr/$LIB64/mozilla/plugins/libflashplayer.so

cd ..
rm -rf flash_player
}

if [ "$EUID" == "0" ]; then
    if [ "$COMMON" == "remove" ]; then
        fp_remove_fun
    elif [ "$COMMON" == "install" ]; then
        # check file
        FILE_NAME=flash_player_npapi_linux.${ARCH}.tar.gz
        if [ ! -f "$FILE_NAME" ]; then
            fp_download_fun
        fi
        fp_install_fun
    else
        echo "Usage: flashplayer install|remove"
    fi
else
    echo "This operation requires root privileges"
    exit 1
fi

