#!/bin/bash

rm -rf /tmp/pkg
mkdir -p /tmp/pkg

echo $@ > /tmp/pkg/pkgname

###############################
loc_pkg_fun(){

PKGNAME=$(cat /tmp/pkg/pkg.tmp | sed -e 's/.pkg.tar.xz>>/.pkg.tar.xz \\\n/'g | sed -e 's/<</\\ /'g)

cat > /tmp/pkg/instpkg << EOF
#!/bin/bash

sudo pacman -U $PKGNAME

EOF
}

###############################

PKG_DETECT=$(cat /tmp/pkg/pkgname | grep .pkg.tar.xz)

if [ "$PKG_DETECT" == "" ]; then
    sudo pacman -S $@
else
    PKG_TMP=$(cat /tmp/pkg/pkgname | sed -e 's/.pkg.tar.xz /.pkg.tar.xz>>/'g | sed -e 's/ /<</'g)
    echo "$PKG_TMP" > /tmp/pkg/pkg.tmp

    LOC_DETECT=$(cat /tmp/pkg/pkg.tmp | grep "<<")
    if [ "$LOC_DETECT" == "" ]; then
        sudo pacman -U $@
    else
        loc_pkg_fun
        sudo chmod 755 /tmp/pkg/instpkg
        /tmp/pkg/instpkg
        rm -rf /tmp/pkg
    fi
fi

