#!/bin/bash

ostype=$(uname -r)
arch=$(uname -m)
distributor=$(lsb_release -i)
fontconfig_ver=$(dpkg -s libfontconfig1 | grep -i version)

sudo rm -rf /etc/apt/apt.conf.d/00recommends
sudo rm -rf /etc/apt/apt.conf
sudo rm /var/lib/apt/lists/*

if [ "$arch" == "x86_64" ]; then
    sudo dpkg --add-architecture i386
fi

case $ostype in
	*"-generic")
        ### Linux Mint / Ubuntu
        sudo add-apt-repository ppa:wine/wine-builds
        sudo apt-get update
	;;
	*"-amd64"|*"-686")
        ### LMDE / Debian
        wget https://dl.winehq.org/wine-builds/Release.key
        sudo apt-key add Release.key
        rm Release.key
        sudo sh -c 'echo "deb http://dl.winehq.org/wine-builds/debian sid main" >> /etc/apt/sources.list.d/wine-official.list'
        sudo apt-get update
	if [ "$distributor" == "Distributor ID:	LinuxMint" ]; then
            if [ "$arch" == "x86_64" ]; then
	        if [ "$fontconfig_ver" == "Version: 2.11.94-0ubuntu1" ]; then
                    wget http://mirrors.kernel.org/ubuntu/pool/main/f/fontconfig/libfontconfig1_2.11.94-0ubuntu1_i386.deb
                    sudo dpkg -i libfontconfig1_*.deb
                    sudo apt-get -f install -y
                    sudo rm libfontconfig1_*.deb
                fi
            fi
        fi
	;;
esac

sudo apt-get install --install-recommends winehq-devel -y

sudo sh -c 'echo "APT::Install-Recommends "false";" > /etc/apt/apt.conf.d/00recommends'
sudo sh -c 'echo "Aptitude::Recommends-Important "false";" >> /etc/apt/apt.conf.d/00recommends'
sudo sed -i 's/false/"false"/g' /etc/apt/apt.conf.d/00recommends

wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x winetricks
sudo cp winetricks /usr/local/bin
rm winetricks

wget https://github.com/Mint-Fans/linux-package/raw/debian/wine-launcher_1.9-0_all.deb
sudo dpkg -i wine-launcher_*.deb
sudo apt-get install xdg-utils -y
rm wine-launcher_*.deb

#############################
### Wine Settings
#############################
## Wine 32-bit for Wine amd64
# WINEARCH=win32 winecfg
winecfg

### font settings
### WenQuanYi Micro Hei
apt-get install fonts-wqy-microhei
cp /usr/share/fonts/truetype/wqy/wqy-microhei.ttc .wine/drive_c/windows/Fonts/
wget https://github.com/Mint-Fans/linux-package/raw/master/wqy-microhei.reg
mv wqy-microhei.reg .wine/drive_c/windows/
wine regedit wqy-microhei.reg

### MingLiU
# wget https://github.com/Mint-Fans/linux-package/raw/master/mingliu.ttc
# mv mingliu.ttc .wine/drive_c/windows/Fonts/
# wget https://github.com/Mint-Fans/linux-package/raw/master/mingliu.reg
# mv mingliu.reg .wine/drive_c/windows/
# wine regedit mingliu.reg


#############################
### Install libraries
#############################
winetricks comctl32
winetricks vb6run

#############################
### Install applications
#############################

wget https://down.xfplay.com/xfplay9.92.exe
wine xfplay9.92.exe

wget http://download.cdn.mozilla.net/pub/firefox/releases/47.0/win32/zh-TW/Firefox%20Setup%2047.0.exe
wine Firefox\ Setup\ 47.0.exe

