#!/bin/bash


#################################################
### iDevice Tools
#################################################
### GTKDialog
if [ "$ARCH" == "amd64" ]; then
    $RUN_IN_CHROOT "wget --no-check-certificate https://github.com/Mint-Fans/linux-package/raw/kali/gtkdialog_0.8.3-1_amd64.deb"
else
    $RUN_IN_CHROOT "wget --no-check-certificate https://github.com/Mint-Fans/linux-package/raw/kali/gtkdialog_0.8.3-1_i386.deb"
fi

$RUN_IN_CHROOT "dpkg -i gtkdialog_*.deb"
$RUN_IN_CHROOT "apt-get -f install -y"
$RUN_IN_CHROOT "rm *.deb"

### Apple IOS Utility
if [ "$ARCH" == "amd64" ]; then
    wget --no-check-certificate http://ftp.us.debian.org/debian/pool/main/i/ifuse/ifuse_1.1.2-0.1+b4_amd64.deb
else
    wget --no-check-certificate http://ftp.us.debian.org/debian/pool/main/i/ifuse/ifuse_1.1.2-0.1+b4_i386.deb
fi

dpkg -i ifuse_*.deb
apt-get -f install -y
rm *.deb

apt-get install libimobiledevice-utils python-imobiledevice libusbmuxd-tools libplist-utils python-plist -y
apt-get install -t jessie usbmuxd -y

if [ "$ARCH" == "amd64" ]; then
    wget --no-check-certificate https://github.com/Mint-Fans/linux-package/raw/kali/libirecovery_0.2.0-2_amd64.deb
else
    wget --no-check-certificate https://github.com/Mint-Fans/linux-package/raw/kali/libirecovery_0.2.0-2_i386.deb
fi

dpkg -i libirecovery_*.deb
apt-get -f install -y
rm *.deb

wget --no-check-certificate https://github.com/Mint-Fans/linux-package/raw/kali/idev-util_0.1-0_all.deb
sudo dpkg -i idev-util_*.deb
sudo apt-get -f install -y
rm *.deb

apt-get install ideviceinstaller ipheth-utils hfsutils hfsplus dmg2img hfsprogs -y

