#!/bin/bash

mkdir fakeroot
mkdir fakeroot/DEBIAN
mkdir fakeroot/usr
mkdir fakeroot/usr/bin
mkdir fakeroot/usr/share
mkdir fakeroot/usr/share/bash-completion
mkdir fakeroot/usr/share/bash-completion/completions
mkdir fakeroot/lib
mkdir fakeroot/lib/systemd
mkdir fakeroot/lib/systemd/system
cp create_ap fakeroot/usr/bin/create_ap
cp create_ap.service fakeroot/lib/systemd/system
cp bash_completion fakeroot/usr/share/bash-completion/completions/create_ap
