#!/bin/bash

###### Translations ###### 
	text1="1).Switching Latest Archlinux Official Repository"
	text2="2).Switching LMAE Repository (ArchLinux mirrorlist 20160320)"
	text3="3).Press 3 or any key to exit"
	text4="Options:"

case $LANG in
	zh_TW* | zh_HK*)
	text1="1).切換 Arch linux 官方最新套件庫"
	text2="2).切換 LMAE 套件庫 (即ArchLinux mirrorlist 20160320)"
	text3="3).按3或其他任意鍵退出"
	text4="輸入選項:"
esac

echo -e "$text1"
echo -e "$text2"
echo -e "$text3"
echo -e ""
echo -e "$text4"

read switch

[[ "$switch" ]] && switch="$switch"

## Latest Archlinux Official Repository
if [ "$switch" == "1" ]; then
	sudo rm -rf /etc/pacman.d/mirrorlist
	sudo cp -rf /etc/pacman.d/pkglist-current /etc/pacman.d/mirrorlist
	sudo rm -rf /var/lib/pacman/sync/*
	sudo pacman -Sy

else
	## LMAE Repository (ArchLinux mirrorlist 20160320)
	if [ "$switch" == "2" ]; then
		sudo sh -c 'echo Server = https://archive.archlinux.org/repos/2016/03/20/$repo/os/$arch > /etc/pacman.d/mirrorlist'
		sudo sed -i 's/\/os\//$repo\/os\/$arch/g' /etc/pacman.d/mirrorlist
		sudo rm -rf /var/lib/pacman/sync/*
		sudo pacman -Sy
	else
        exit 0
	fi
fi
