ANDROID_NDK_PATH=/media/kali/WORK/Build-Tools/android-ndk-r12b

# Settings API
export ANDROID_API=24

# Build armv7 32-bit
export ANDROID_ARCH=arm
CROSS_COMPILE=arm-linux-androideabi

# Build armv8 64-bit
export ANDROID_ARCH=arm64
CROSS_COMPILE=aarch64-linux-android

export SYSTEM=android
export ANDROID_NDK_ROOT=$ANDROID_NDK_PATH
export ANDROID_TOOLCHAIN=$ANDROID_NDK_ROOT/toolchains/"$CROSS_COMPILE"-4.9/prebuilt/linux-x86_64/bin
export PATH=$PATH:$ANDROID_TOOLCHAIN

export ANDROID_SYSROOT=$ANDROID_NDK_ROOT/platforms/android-"$ANDROID_API"/arch-"$ANDROID_ARCH"
export CROSS_SYSROOT=$ANDROID_SYSROOT
export NDK_SYSROOT=$ANDROID_SYSROOT
export SYSROOT=$ANDROID_SYSROOT
export NDK_SYSROOT=$ANDROID_SYSROOT
export ANDROID_NDK_SYSROOT=$ANDROID_SYSROOT
export ANDROID_DEV=$ANDROID_SYSROOT/usr

export CC=$ANDROID_TOOLCHAIN/"$CROSS_COMPILE"-gcc
export CXX=$ANDROID_TOOLCHAIN/"$CROSS_COMPILE"-g++
export LD=$ANDROID_TOOLCHAIN/"$CROSS_COMPILE"-ld
export AR=$ANDROID_TOOLCHAIN/"$CROSS_COMPILE"-ar
export AS=$ANDROID_TOOLCHAIN/"$CROSS_COMPILE"-as
export NM=$ANDROID_TOOLCHAIN/"$CROSS_COMPILE"-nm
export RANLIB=$ANDROID_TOOLCHAIN/"$CROSS_COMPILE"-ranlib
