#!/bin/bash


DISTRIB=$(uname -r)

### Debian
DPKG_ARCH=$(cat /var/lib/dpkg/arch | grep i386)

if [ "$DPKG_ARCH" == "i386" ]; then
    DPKG_I386='y'
else
    DPKG_I386='n'
fi

### Arch Linux
MULTLIB_STATUS=$(cat /etc/pacman.conf |grep multilib] | tail -n 1)

if [ "$MULTLIB_STATUS" == "[multilib]" ]; then
    MULT32LIB='y'
else
    MULT32LIB='n'
fi


main_fun(){
clear
echo -e ""
echo -e "    NVIDIA Optimus Driver [bumblebee]"
echo -e ""
echo -e "    1) Install NVIDIA Optimus Driver"

if [ "$(uname -m)" == "x86_64" ]; then
    if [ -d "/var/lib/dpkg" ]; then
        if [ ! "$DPKG_I386" == "y" ]; then
            echo -e "    2) Enable i386 Repository for Debian (i386: $DPKG_I386)"
        fi
    fi

    if [ -d "/var/lib/pacman" ]; then
        if [ ! "$MULT32LIB" == "y" ]; then
            echo -e "    2) Enable multilib Repository for ArchLinux (multilib: $MULT32LIB)"
        fi
    fi
fi

echo -e "    0) Press 0 or Any key to Exit"
echo -e ""
echo -e "    Enter Options:"

read menu
[[ "$menu" ]] && menu="$menu"

if [ "$menu" == "1" ]; then
    case $DISTRIB in
        *"-amd64"|*"-686") debian_nv_fun;;
        *"-ARCH") arch_nv_fun;;
    esac
else
    if [ "$menu" == "2" ]; then
        case $DISTRIB in
            *"-amd64"|*"-686") i386_repo_fun;;
            *"-ARCH") multilib_fun;;
        esac
    else
        exit
    fi
fi
}

i386_repo_fun(){
clear
cat << ENTER
    Enable i386 Repository 

    (Status: $DPKG_I386) Options[y/n]
ENTER

read DPKG_I386
[[ "$DPKG_I386" ]] && DPKG_I386="$DPKG_I386"
if [ ! "$DPKG_I386" == "y" ]; then
    DPKG_I386='n'
fi

if [ "$DPKG_I386" == "y" ]; then
    sudo dpkg --add-architecture i386
fi

main_fun

}

multilib_fun(){
clear
cat << ENTER
    Enable multilib Repository

    (Status: $MULT32LIB) Options[y/n]
ENTER

read MULT32LIB
[[ "$MULT32LIB" ]] && MULT32LIB="$MULT32LIB"
if [ ! "$MULT32LIB" == "y" ]; then
    MULT32LIB='n'
fi

if [ "$MULT32LIB" == "y" ]; then
    sudo sh -c 'echo "[multilib]" >> /etc/pacman.conf'
    sudo sh -c 'echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf'
fi

main_fun

}


debian_nv_fun(){

sudo apt-get update

### Intel Driver
sudo apt-get install xserver-xorg-video-intel libdrm-intel1 -y

if [ "$DPKG_I386" == "y" ]; then
    sudo apt-get install libdrm-intel1:i386 -y
fi

sudo apt-get install vainfo intel-gpu-tools -y

### NVIDIA Optimus
# sudo apt-get --purge remove xserver-xorg-video-nouveau -y
sudo apt-get --purge remove bumblebee* bbswitch-dkms -y
sudo apt-get --purge remove ubuntu-drivers-common -y
sudo apt autoremove

sudo apt-get install bumblebee-nvidia primus -y
sudo apt-get install nvidia-settings nvidia-xconfig mesa-utils -y

### For 32-bit applications support on 64-bit machines
if [ "$DPKG_I386" == "y" ]; then
    sudo apt-get install primus-libs:i386 -y
fi

sudo sed -i 's/Exec=nvidia-settings/Exec=sudo optirun -b none nvidia-settings -c :8/g' /usr/lib/nvidia/current/nvidia-settings.desktop

# NV_BUSID=$(lspci |grep NVIDIA | sed -e 's/ .*//g')

# if [ ! "$NV_BUSID" == "" ]; then
#     sudo sed -i s/01:00:0/$NV_BUSID/g /etc/bumblebee/xorg.conf.nvidia
#     sudo sed -i 's/#   BusID/    BusID/g' /etc/bumblebee/xorg.conf.nvidia
# fi

# sudo sed -i 's/BusID/#BusID/g' /etc/bumblebee/xorg.conf.nouveau

exit

}

arch_nv_fun(){

wget https://github.com/Mint-Fans/linux-package/raw/arch/mirrorlist-backup.tar.gz
tar -zxvf mirrorlist-backup.tar.gz
sudo rm -rf /etc/pacman.d/pkglist-current
sudo rm -rf /etc/pacman.d/mirrorlist.pacnew
sudo rm -rf /etc/pacman.d/mirrorlist
sudo mv pkglist-current /etc/pacman.d/
sudo mv mirrorlist.pacnew /etc/pacman.d/
sudo rm mirrorlist-backup.tar.gz
sudo cp /etc/pacman.d/pkglist-current /etc/pacman.d/mirrorlist
sudo pacman -Sy

### Intel Driver
sudo pacman -S --noconfirm xf86-video-intel libva-intel-driver libva

### NVIDIA Optimus
sudo pacman -S --noconfirm bumblebee bbswitch primus nvidia nvidia-utils opencl-nvidia nvidia-settings
sudo gpasswd -a $USER bumblebee
sudo systemctl enable bumblebeed.service
sudo systemctl start bumblebeed.service

### For 32-bit applications support on 64-bit machines
if [ "$MULT32LIB" == "y" ]; then
    sudo pacman -S --noconfirm lib32-primus lib32-nvidia-utils lib32-mesa-libgl lib32-mesa
fi

sudo sed -i 's/Exec=\/usr\/bin\/nvidia-settings/Exec=sudo optirun -b none nvidia-settings -c :8/g' /usr/share/applications/nvidia-settings.desktop

# NV_BUSID=$(lspci |grep NVIDIA | sed -e 's/ .*//g')

# if [ ! "$NV_BUSID" == "" ]; then
#     sudo sed -i s/01:00:0/$NV_BUSID/g /etc/bumblebee/xorg.conf.nvidia
#     sudo sed -i 's/#   BusID/    BusID/g' /etc/bumblebee/xorg.conf.nvidia
# fi

# sudo sed -i 's/BusID/#BusID/g' /etc/bumblebee/xorg.conf.nouveau

exit
}

main_fun

