#!/bin/bash


#####################################
OPT=$1
PKGNAME=$2

#####################################
pkglist_fun(){
clear
echo -e ""
echo -e "    Find PKG Info"
echo -e ""
echo -e "    Enter the package name"
echo -e ""
read PKGNAME
[[ "$PKGNAME" ]]

if [ "$PKGNAME" == "" ]; then
    echo -e "   The PKG Name is not entered"
    exit
else
    pkginfo | grep "$PKGNAME"
fi

menu_fun

}

#####################################
inst_pkg_fun(){
clear
echo -e ""
echo -e "    PKG Install"
echo -e ""
echo -e "    Drag and Drop the PKG Here"
echo -e ""
read PKGFILE
[[ "$PKGFILE" ]]
if [ "$PKGFILE" == "" ]; then
    echo -e "   The PKGFILE is not entered"
    exit
fi

pkgadd -d $PKGFILE all

menu_fun
}

#####################################
rm_pkg_fun(){
clear
echo -e ""
echo -e "    PKG Remove"
echo -e ""
echo -e "    Enter the PKG name"
echo -e ""
read PKGNAME
[[ "$PKGNAME" ]]

if [ "$PKGNAME" == "" ]; then
    echo -e "   The PKG Name is not entered"
    menu_fun
else
    pkginfo | grep "$PKGNAME"
fi

echo -e ""
echo -e "    Enter the package"
echo -e ""
read PKG
[[ "$PKG" ]]
if [ "$PKG" == "" ]; then
    echo -e "   The package is not entered"
    exit
fi

pkgrm $PKG

menu_fun
}

#####################################
menu_fun(){
clear
echo -e ""
echo -e "    PKG Management"
echo -e ""
echo -e "    1) Install PKG"
echo -e ""
echo -e "    2) remove PKG"
echo -e ""
echo -e "    3) View Installed PKG"
echo -e ""
read MENU
[[ "$MENU" ]]

if [ "$MENU" == "1" ]; then
    inst_pkg_fun
elif [ "$MENU" == "2" ]; then
    rm_pkg_fun
elif [ "$MENU" == "3" ]; then
    pkglist_fun
else
    exit
fi

}

#####################################
if [ "$OPT" == "rm" ]; then
    pkgrm $PKGNAME
elif [ "$OPT" == "inst" ]; then
    pkgadd -d $PKGNAME all
elif [ "$OPT" == "info" ]; then
    if [ "$PKGNAME" == "" ]; then
        pkglist_fun
    else
        pkginfo | grep "$PKGNAME"
    fi
elif [ "$OPT" == "" ]; then
    menu_fun
fi


