#!/bin/bash


#####################################
pkgupk_fun(){
clear
echo -e ""
echo -e "    Solaris 10 PKG Unpack"
echo -e ""
echo -e "    Drag and Drop the PKG Here"
echo -e ""
read PKGFILE
[[ "$PKGFILE" ]]

if [ "$PKGFILE" == "" ]; then
    echo -e "   The PKGFILE is not entered"
    exit
fi

mkdir -p /Documents/pkg
rm -rf /Documents/pkg/*
pkgtrans "$PKGFILE" /Documents/pkg/

echo -e "    PKG decompression is successful."

exit

}

#####################################
pkgupk_fun


