#!/bin/bash


VER='47.0'

# LANG=ja
# LANG=zh-TW
LANG=$(locale | grep LANG | sed -e 's/.UTF-8//g' | sed -e 's/LANG=//g' | sed -e 's/_/-/g')

if [ "$(uname -m)" == "x86_64" ]; then
    ARCH=x86_64
else
    ARCH=i686
fi

# http://download.cdn.mozilla.net/pub/firefox/releases/47.0/linux-x86_64/zh-TW/firefox-47.0.tar.bz2
# http://download.cdn.mozilla.net/pub/firefox/releases/47.0/linux-i686/zh-TW/firefox-47.0.tar.bz2

wget http://download.cdn.mozilla.net/pub/firefox/releases/"$VER"/linux-"$ARCH"/"$LANG"/firefox-"$VER".tar.bz2
tar jxvf firefox-"$VER".tar.bz2

rm -rf firefox/browser/crashreporter-override.ini
# rm -rf firefox/browser/features/e10srollout@mozilla.org.xpi
# rm -rf firefox/browser/features/firefox@getpocket.com.xpi
rm -rf firefox/dictionaries
rm -rf firefox/icons
rm firefox/crashreporter
rm firefox/crashreporter.ini
rm firefox/libfreebl3.chk
rm firefox/libfreebl3.so
rm firefox/libmozavcodec.so
rm firefox/libmozavutil.so
rm firefox/libnssckbi.so
rm firefox/libnssdbm3.chk
rm firefox/libnssdbm3.so
rm firefox/libsoftokn3.chk
rm firefox/libsoftokn3.so
rm firefox/precomplete
rm firefox/Throbber-small.gif
rm firefox/update-settings.ini
rm firefox/updater
rm firefox/updater.ini

sed -i '/SourceRepository/d' firefox/application.ini
sed -i '/SourceStamp/d' firefox/application.ini
sed -i '/Enabled/d' firefox/application.ini
sed -i '/ServerURL/d' firefox/application.ini
sed -i '/Reporter/d' firefox/application.ini
sed -i '/SourceRepository/d' firefox/platform.ini
sed -i '/SourceStamp/d' firefox/platform.ini
sed -i '/Enabled/d' firefox/webapprt/webapprt.ini
sed -i 's/release/default/g' firefox/defaults/pref/channel-prefs.js

mkdir -p firefox/browser/defaults
mkdir -p firefox/browser/defaults/preferences
wget https://github.com/Mint-Fans/linux-package/raw/master/vendor.js
mv vendor.js firefox/browser/defaults/preferences/

rm -rf /usr/lib/firefox
mv firefox /usr/lib/

rm firefox-*.tar.bz2
rm -rf /home/*/.mozilla
rm -rf /root/.mozilla
