#!/bin/bash


wget https://www.mozilla.org/en-US/firefox/new/index.html

# VER='47.0.1'
VER=$(cat index.html | grep softwareVersion 2>&1 | sed -e 's/">//g' | sed -e 's/  <meta itemprop="softwareVersion" content="//g' )

rm index.html

# LANG=ja
# LANG=zh-TW
LANG=$(locale -a | grep utf8 2>&1 | sed -e 's/.utf8//g' | sed -e 's/_/-/g' | tail -n 1 )

if [ "$(uname -m)" == "x86_64" ]; then
    ARCH=x86_64
else
    ARCH=i686
fi

### 範例
# http://download.cdn.mozilla.net/pub/firefox/releases/47.0/linux-x86_64/zh-TW/firefox-47.0.tar.bz2
# http://download.cdn.mozilla.net/pub/firefox/releases/47.0/linux-i686/zh-TW/firefox-47.0.tar.bz2

wget http://download.cdn.mozilla.net/pub/firefox/releases/"$VER"/linux-"$ARCH"/"$LANG"/firefox-"$VER".tar.bz2
tar jxvf firefox-"$VER".tar.bz2

rm -rf firefox/browser/crashreporter-override.ini
# rm -rf firefox/browser/features/e10srollout@mozilla.org.xpi
# rm -rf firefox/browser/features/firefox@getpocket.com.xpi
# rm -rf firefox/dictionaries
rm -rf firefox/icons
rm firefox/crashreporter
rm firefox/crashreporter.ini
# rm firefox/libfreebl3.chk
# rm firefox/libfreebl3.so
# rm firefox/libmozavcodec.so
# rm firefox/libmozavutil.so
# rm firefox/libnssckbi.so
# rm firefox/libnssdbm3.chk
# rm firefox/libnssdbm3.so
# rm firefox/libsoftokn3.chk
# rm firefox/libsoftokn3.so
# rm firefox/precomplete
# rm firefox/Throbber-small.gif
rm firefox/update-settings.ini
rm firefox/updater
rm firefox/updater.ini

sed -i '/SourceRepository/d' firefox/application.ini
sed -i '/SourceStamp/d' firefox/application.ini
sed -i '/Enabled/d' firefox/application.ini
sed -i '/ServerURL/d' firefox/application.ini
sed -i '/Reporter/d' firefox/application.ini
sed -i '/SourceRepository/d' firefox/platform.ini
sed -i '/SourceStamp/d' firefox/platform.ini
sed -i '/Enabled/d' firefox/webapprt/webapprt.ini
sed -i 's/release/default/g' firefox/defaults/pref/channel-prefs.js

mkdir -p firefox/browser/defaults/preferences

### /usr/lib/firefox/browser/defaults/preferences/vendor.js
cat > firefox/browser/defaults/preferences/vendor.js << EOF
// Use LANG environment variable to choose locale
pref("intl.locale.matchOS", true);

// Disable application updates
pref("app.update.auto", false);
pref("app.update.enabled", false);

// Disable default browser checking.
pref("browser.shell.checkDefaultBrowser", false);

// Disable OpenH264 Decoder
pref("media.gmp-gmpopenh264.enabled", false);

// Don't disable our bundled extensions in the application directory
pref("extensions.autoDisableScopes", 11);
pref("extensions.shownSelectionUI", true);
EOF

sudo rm -rf /usr/lib/firefox
sudo rm -rf /usr/share/firefox
sudo mv firefox /usr/lib/

rm -rf /home/*/.mozilla
sudo rm -rf /root/.mozilla

rm firefox-*.tar.bz2
