#!/bin/bash

###############################################
### Update GLX 390
###############################################
LIB64=
LIB32=
XMOD_PATH=
NV_XMOD_PATH=

DISPLAY_TYPE=$(lspci | grep 'VGA' | awk '{print $5}')
NV_VER=$(modinfo nvidia | grep ^version | awk '{print $2}')

###############################################
install_nvglx_fun(){
echo "Install NVIDIA X Library --->"
# install nvidia x library
mv $XMOD_PATH/extensions/libglx.so $XMOD_PATH/extensions/libglx_xorg.so
ln -sf ../../../nvidia/xorg/libglx.so $XMOD_PATH/extensions/libglx.so

# backup mesa glx
LIB64_MESA_GL=$(ls -l $LIB64/ | grep libGL.so.1 | grep '>' | awk '{print $11}')
LIB64_MESA_EGL=$(ls -l $LIB64/ | grep libEGL.so.1 | grep '>' | awk '{print $11}')
LIB64_MESA_GLX=$(ls -l $LIB64/ | grep libGLX_indirect.so.0 | grep '>' | awk '{print $11}')

LIB32_MESA_GL=$(ls -l $LIB32/ | grep libGL.so.1 | grep '>' | awk '{print $11}')
LIB32_MESA_EGL=$(ls -l $LIB32/ | grep libEGL.so.1 | grep '>' | awk '{print $11}')
LIB32_MESA_GLX=$(ls -l $LIB32/ | grep libGLX_indirect.so.0 | grep '>' | awk '{print $11}')

mkdir -p $NV_XMOD_PATH/mesa

echo $LIB64_MESA_GL > $NV_XMOD_PATH/mesa/LIB64_MESA_GL
echo $LIB64_MESA_EGL > $NV_XMOD_PATH/mesa/LIB64_MESA_EGL
echo $LIB64_MESA_GLX > $NV_XMOD_PATH/mesa/LIB64_MESA_GLX

echo $LIB32_MESA_GL > $NV_XMOD_PATH/mesa/LIB32_MESA_GL
echo $LIB32_MESA_EGL > $NV_XMOD_PATH/mesa/LIB32_MESA_EGL
echo $LIB32_MESA_GLX > $NV_XMOD_PATH/mesa/LIB32_MESA_GLX

# install glx
echo "Install NVIDIA GLX/GL Library --->"
rm -rf $LIB64/libEGL_nvidia.so.0
rm -rf $LIB64/libGLESv1_CM_nvidia.so.1
rm -rf $LIB64/libGLESv2_nvidia.so.2
rm -rf $LIB64/libGLX_nvidia.so.0
rm -rf $LIB64/libEGL.so.1
rm -rf $LIB64/libGL.so.1
rm -rf $LIB64/libGLX_indirect.so.0

rm -rf $LIB32/libEGL_nvidia.so.0
rm -rf $LIB32/libGLESv1_CM_nvidia.so.1
rm -rf $LIB32/libGLESv2_nvidia.so.2
rm -rf $LIB32/libGLX_nvidia.so.0
rm -rf $LIB32/libEGL.so.1
rm -rf $LIB32/libGL.so.1
rm -rf $LIB32/libGLX_indirect.so.0

ln -sf nvidia/libEGL_nvidia.so.0 $LIB64/libEGL_nvidia.so.0
ln -sf nvidia/libGLESv1_CM_nvidia.so.1 $LIB64/libGLESv1_CM_nvidia.so.1
ln -sf nvidia/libGLESv2_nvidia.so.2 $LIB64/libGLESv2_nvidia.so.2
ln -sf nvidia/libGLX_nvidia.so.0 $LIB64/libGLX_nvidia.so.0
cp $LIB64/nvidia/libEGL.so.${NV_VER} $LIB64/libEGL.so.1
cp $LIB64/nvidia/libGL.so.${NV_VER} $LIB64/libGL.so.1
cp $LIB64/nvidia/libGLX_nvidia.so.${NV_VER} $LIB64/libGLX_indirect.so.0

ln -sf nvidia/libEGL_nvidia.so.0 $LIB32/libEGL_nvidia.so.0
ln -sf nvidia/libGLESv1_CM_nvidia.so.1 $LIB32/libGLESv1_CM_nvidia.so.1
ln -sf nvidia/libGLESv2_nvidia.so.2 $LIB32/libGLESv2_nvidia.so.2
ln -sf nvidia/libGLX_nvidia.so.0 $LIB32/libGLX_nvidia.so.0
cp $LIB32/nvidia/libEGL.so.${NV_VER} $LIB32/libEGL.so.1
cp $LIB32/nvidia/libGL.so.${NV_VER} $LIB32/libGL.so.1
cp $LIB32/nvidia/libGLX_nvidia.so.${NV_VER} $LIB32/libGLX_indirect.so.0
}

###############################################
remove_nvglx_fun(){
echo "Remove NVIDIA X Library --->"
# remove nvidia x library
rm -rf $XMOD_PATH/extensions/libglx.so
mv $XMOD_PATH/extensions/libglx_xorg.so $XMOD_PATH/extensions/libglx.so

# remove glx
echo "Remove NVIDIA GLX/GL Library --->"
rm -rf $LIB64/libEGL_nvidia.so.0
rm -rf $LIB64/libGLESv1_CM_nvidia.so.1
rm -rf $LIB64/libGLESv2_nvidia.so.2
rm -rf $LIB64/libGLX_nvidia.so.0
rm -rf $LIB64/libEGL.so.1
rm -rf $LIB64/libGL.so.1
rm -rf $LIB64/libGLX_indirect.so.0

rm -rf $LIB32/libEGL_nvidia.so.0
rm -rf $LIB32/libGLESv1_CM_nvidia.so.1
rm -rf $LIB32/libGLESv2_nvidia.so.2
rm -rf $LIB32/libGLX_nvidia.so.0
rm -rf $LIB32/libEGL.so.1
rm -rf $LIB32/libGL.so.1
rm -rf $LIB32/libGLX_indirect.so.0

# restore glx
LIB64_MESA_GL=$(cat $NV_XMOD_PATH/mesa/LIB64_MESA_GL)
LIB64_MESA_EGL=$(cat $NV_XMOD_PATH/mesa/LIB64_MESA_EGL)
LIB64_MESA_GLX=$(cat $NV_XMOD_PATH/mesa/LIB64_MESA_GLX)

LIB32_MESA_GL=$(cat $NV_XMOD_PATH/mesa/LIB32_MESA_GL)
LIB32_MESA_EGL=$(cat $NV_XMOD_PATH/mesa/LIB32_MESA_EGL)
LIB32_MESA_GLX=$(cat $NV_XMOD_PATH/mesa/LIB32_MESA_GLX)

ln -sT $LIB64_MESA_GL $LIB64/libGL.so.1 > /dev/null 2>&1
ln -sT $LIB64_MESA_EGL $LIB64/libEGL.so.1 > /dev/null 2>&1
ln -sT $LIB64_MESA_GLX $LIB64/libGLX_nvidia.so.0 > /dev/null 2>&1

ln -sT $LIB32_MESA_GL $LIB32/libGL.so.1 > /dev/null 2>&1
ln -sT $LIB32_MESA_EGL $LIB32/libEGL.so.1 > /dev/null 2>&1
ln -sT $LIB32_MESA_GLX $LIB32/libGLX_nvidia.so.0 > /dev/null 2>&1

rm -rf $NV_XMOD_PATH/mesa
}

###############################################
if [ "$DISPLAY_TYPE" == "NVIDIA" ]; then
    if [ "$1" == "install" ]; then
        install_nvglx_fun
        echo "run nvidia-xconfig --->"
        nvidia-xconfig > /dev/null 2>&1
    fi
    if [ "$1" == "remove" ]; then
        remove_nvglx_fun
        echo "remove nvidia xorg config --->"
        rm -rf /etc/X11/xorg.conf
        rm -rf /etc/X11/xorg.conf.nvidia-xconfig-original
    fi
else
    echo 'NVIDIA Optimus --->'
fi
