#!/bin/bash


wget https://www.adobe.com/software/flash/about/

if [ "$(uname -m)" == "x86_64" ]; then
    ARCH=x86_64
else
    ARCH=i386
fi

CURRENT_VER=$(cat index.html | grep "<td>2" | sed -e 's/.*<td>//g' | sed -e 's/<\/td>.*//g' | tail -n 1)

rm index.html

### Update Adobe official Flash Player
ADOBE_OFFCOAL=https://fpdownload.adobe.com/get/flashplayer/pdc/"$CURRENT_VER"/flash_player_npapi_linux."$ARCH".tar.gz

FLASH_PLAYER_PACKAGE=flash_player_npapi_linux."$ARCH".tar.gz

DISTRIB=$(uname -r)

mkdir -p flash_player
cd flash_player
wget $ADOBE_OFFCOAL
tar zxvf $FLASH_PLAYER_PACKAGE

sudo rm -rf /usr/share/icons/hicolor/16x16/apps/flash-player-properties.png
sudo rm -rf /usr/share/icons/hicolor/22x22/apps/flash-player-properties.png
sudo rm -rf /usr/share/icons/hicolor/24x24/apps/flash-player-properties.png
sudo rm -rf /usr/share/icons/hicolor/32x32/apps/flash-player-properties.png
sudo rm -rf /usr/share/icons/hicolor/48x48/apps/flash-player-properties.png
sudo cp usr/share/icons/hicolor/16x16/apps/flash-player-properties.png /usr/share/icons/hicolor/16x16/apps/
sudo cp usr/share/icons/hicolor/22x22/apps/flash-player-properties.png /usr/share/icons/hicolor/22x22/apps/
sudo cp usr/share/icons/hicolor/24x24/apps/flash-player-properties.png /usr/share/icons/hicolor/24x24/apps/
sudo cp usr/share/icons/hicolor/32x32/apps/flash-player-properties.png /usr/share/icons/hicolor/32x32/apps/
sudo cp usr/share/icons/hicolor/48x48/apps/flash-player-properties.png /usr/share/icons/hicolor/48x48/apps/
sudo rm -rf /usr/share/pixmaps/flash-player-properties.png
sudo ln -s /usr/share/icons/hicolor/48x48/apps/flash-player-properties.png /usr/share/pixmaps/flash-player-properties.png

sudo rm -rf /usr/share/applications/flash-player-properties.desktop
sudo cp usr/share/applications/flash-player-properties.desktop /usr/share/applications/

sudo rm /usr/bin/flash-player-properties
sudo cp usr/bin/flash-player-properties /usr/bin/


if [ -d "/usr/lib/kde4" ]; then
    sudo rm -rf /usr/share/kde4/services/kcm_adobe_flash_player.desktop
    sudo cp usr/share/kde4/services/kcm_adobe_flash_player.desktop /usr/share/kde4/services/

    if [ "$ARCH" == "x86_64" ]; then
        sudo rm -rf /usr/lib/kde4/kcm_adobe_flash_player.so
        sudo cp usr/lib64/kde4/kcm_adobe_flash_player.so /usr/lib/kde4/
    else
        sudo rm -rf /usr/lib/kde4/kcm_adobe_flash_player.so
        sudo cp usr/lib/kde4/kcm_adobe_flash_player.so /usr/lib/kde4/
    fi
fi

case $DISTRIB in
	*"-generic")
	### Ubuntu / Linux Mint
	sudo rm /usr/lib/flashplugin-installer/libflashplayer.so
	sudo mkdir -p /usr/lib/flashplugin-installer
	sudo cp libflashplayer.so /usr/lib/flashplugin-installer/
	sudo update-alternatives --quiet --remove "mozilla-flashplugin" /usr/lib/flashplugin-installer/libflashplayer.so
	sudo update-alternatives --quiet --install "/usr/lib/mozilla/plugins/flashplugin-alternative.so" "mozilla-flashplugin" /usr/lib/flashplugin-installer/libflashplayer.so 50
	;;

	*"-amd64"|*"-686")
	### Debian / LMDE
	sudo rm /usr/lib/flashplugin-nonfree/libflashplayer.so
	sudo mkdir -p /usr/lib/flashplugin-nonfree
	sudo cp libflashplayer.so /usr/lib/flashplugin-nonfree/
	sudo update-alternatives --quiet --remove flash-mozilla.so /usr/lib/flashplugin-nonfree/libflashplayer.so
	sudo update-alternatives --quiet --install /usr/lib/mozilla/plugins/flash-mozilla.so flash-mozilla.so /usr/lib/flashplugin-nonfree/libflashplayer.so 50
	;;

	*"-ARCH")
	### Arch Linux / LMAE
	sudo rm /usr/lib/mozilla/plugins/libflashplayer.so
	sudo mkdir -p /usr/lib/mozilla/plugins
	sudo cp libflashplayer.so /usr/lib/mozilla/plugins/
	;;
esac

cd ../
sudo rm -rf flash_player
